---
# handlers file for anaconda

- name: Enable Jupyter
  systemd:
    name: jupyterlab
    enabled: yes
  listen: "enable jupyterlab"

- name: Restart Jupyterlab
  systemd:
    name: jupyterlab
    state: restarted
    daemon_reload: yes
  listen: 'restart jupyterlab'
